# Generated by Django 5.1.2 on 2024-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicado'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
